### ISSUE TITLE
Proposal: investigate doing cluster level locking using the k8s API

### ISSUE THREAD

**Issue by arschles** [deis/riak#21]
See http://stackoverflow.com/questions/34409160/kubernetes-getting-cluster-locks-over-a-replication - it indicates a usage of [Annotations](http://kubernetes.io/v1.1/docs/user-guide/annotations.html)

**Comment by aledbf** [comment]
@arschles please check [election](https://github.com/kubernetes/contrib/tree/master/election) [post](blog.kubernetes.io/2016/01/simple-leader-election-with-Kubernetes.html)

**Comment by arschles** [comment]
@aledbf thanks, I had seen that. It doesn't completely fit the needs of this particular issue (but may in others, such as electing the [stanchion](http://docs.basho.com/riakcs/latest/theory/stanchion/)), because essentially we need to lock/unlock frequently during the bootstrap/scale event.

We _could_ potentially use a leader to orchestrate the lock, but as of now, using compare-and-set against `ResourceVersion`s on a service annotation (a very similar strategy as leader election takes) seems to be the best strategy for this particular issue. Thoughts?
