### ISSUE TITLE
deis/riak:latest on Docker Hub is broken

### ISSUE THREAD

**Issue by mboersma** [deis/riak#28]
The Dockerfile specifies `/bin/boot` as the executable, but that binary is missing from the current `deis/riak:latest` image at Docker Hub. This breaks `helm` CI testing since the [`riak`](https://github.com/helm/charts/tree/master/riak) chart cannot deploy successfully.

**Comment by bacongobbler** [comment]
This seems to be a limitation of docker's automated build system. Our dev cycle requires that we run `glide up` then `make` to compile the Go binaries, copy them into `rootfs`, and finally build and push the image to the targeted registry. We should probably build this into Travis instead.
