### ISSUE TITLE
Automatically plan and commit the cluster

### ISSUE THREAD

**Issue by arschles** [deis/riak#8]
The current instructions for starting or scaling the cluster include two manual steps:
- Planning the cluster: `kubectl exec deis-riak-bootstrap riak-admin cluster plan`
- Committing the plan: `kubectl exec deis-riak-bootstrap riak-admin cluster commit`

In fact, these steps need to be done after any change in the Riak cluster topology, which includes a pod crashing and being restarted by Kubernetes. It's unacceptable for a cluster administrator to have to run those commands when they start or scale their Riak cluster, and especially so when Kubernetes automatically changes the topology. This component should take care of doing the plan and commit instead.

Ideas that should be tested:
1. Just run `riak-admin cluster plan && riak-admin cluster commit` after each `riak-admin cluster join` command (in nodes that are added to the cluster)
2. Build a simple API into the bootstrap pod that newly added pods can call with their node name. The API can then call the `cluster plan && cluster commit` calls in response. I'm not sure right now if this would be beneficial over option 1

**Comment by bacongobbler** [comment]
> Just run riak-admin cluster plan && riak-admin cluster commit after each riak-admin cluster join command (in nodes that are added to the cluster)

My main concern with this was cluster operation load as it balances out data across the cluster, though that would be a good first step. e.g. we have three nodes and we scale out to 100. Does that mean we have to plan and commit 97 times? Might be some dragons lying in Riak there.

Other things to consider would also be like nodes removing themselves from the cluster as they gently shut down via `riak-admin cluster leave`. See http://docs.basho.com/riak/latest/ops/running/nodes/adding-removing/#Removing-a-Node-From-a-Cluster for more details. Note that this won't handle the case when a node is (rudely) shut down, so we'd need to have backup plans for that situation as well.

**Comment by arschles** [comment]
> My main concern with this was cluster operation load as it balances out data across the cluster, though that would be a good first step.

Agreed, it would be a good first step. Option 2 may be beneficial because we could serialize `plan`s and `commit`s using that server. 

> Other things to consider would also be like nodes removing themselves from the cluster as they gently shut down via riak-admin cluster leave

I'm going to consider this another issue, and I've created #9 to capture it. Regarding a rude shutdown, Riak is designed to detect the loss and automatically rebalance data around the ring. We can "get away" with that for now, and calling `riak-admin cluster leave` is certainly an optimization.
